from .cadastro import cadastro
from .calendario import calendario
from .classificacao import classificacao
from .equipes import equipes
from .index import index
from .login import login
from .pilotos import pilotos
from .logout import logout
from .criar_funcao import criar_funcao
from .listar_usuarios import listar_usuarios
from .editar_usuario import editar_usuario
from .remover_funcao import remover_funcao