"""Migração inicial

Revision ID: e0f5028ffd48
Revises: 
Create Date: 2019-04-25 23:03:16.351176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f5028ffd48'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pais',
    sa.Column('id_pais', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_pais', sa.String(length=65), nullable=False),
    sa.PrimaryKeyConstraint('id_pais'),
    sa.UniqueConstraint('nome_pais')
    )
    op.create_table('cidade',
    sa.Column('id_cidade', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_cidade', sa.String(length=50), nullable=False),
    sa.Column('id_pais', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pais'], ['pais.id_pais'], ),
    sa.PrimaryKeyConstraint('id_cidade'),
    sa.UniqueConstraint('nome_cidade')
    )
    op.create_table('circuito',
    sa.Column('id_circuito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_circuito', sa.String(length=100), nullable=False),
    sa.Column('percurso', sa.Integer(), nullable=True),
    sa.Column('numero_voltas', sa.Integer(), nullable=True),
    sa.Column('distancia_total', sa.Integer(), nullable=True),
    sa.Column('primeira_corrida', sa.Integer(), nullable=True),
    sa.Column('piloto_recorde_pista', sa.String(length=50), nullable=True),
    sa.Column('ano_recorde_pista', sa.Integer(), nullable=True),
    sa.Column('tempo_recorde_pista', sa.Time(), nullable=True),
    sa.Column('id_cidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cidade'], ['cidade.id_cidade'], ),
    sa.PrimaryKeyConstraint('id_circuito'),
    sa.UniqueConstraint('nome_circuito')
    )
    op.create_table('equipe',
    sa.Column('id_equipe', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_equipe', sa.String(length=50), nullable=False),
    sa.Column('nome_oficial', sa.String(length=125), nullable=False),
    sa.Column('numero_titulos', sa.Integer(), nullable=True),
    sa.Column('nr_voltas_mais_rapidas', sa.Integer(), nullable=True),
    sa.Column('nr_pole_positions', sa.Integer(), nullable=True),
    sa.Column('unidade_potencia', sa.String(length=75), nullable=True),
    sa.Column('chassi', sa.String(length=15), nullable=True),
    sa.Column('melhor_resultado', sa.String(length=25), nullable=True),
    sa.Column('id_cidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cidade'], ['cidade.id_cidade'], ),
    sa.PrimaryKeyConstraint('id_equipe'),
    sa.UniqueConstraint('nome_equipe'),
    sa.UniqueConstraint('nome_oficial')
    )
    op.create_table('evento',
    sa.Column('id_evento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_evento', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_termino', sa.Date(), nullable=True),
    sa.Column('id_circuito', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_circuito'], ['circuito.id_circuito'], ),
    sa.PrimaryKeyConstraint('id_evento'),
    sa.UniqueConstraint('nome_evento')
    )
    op.create_table('piloto',
    sa.Column('id_piloto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_piloto', sa.String(length=100), nullable=False),
    sa.Column('pontos_ganhos', sa.Integer(), nullable=True),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('numero_piloto', sa.Integer(), nullable=True),
    sa.Column('corridas_disputadas', sa.Integer(), nullable=True),
    sa.Column('numero_podios', sa.Integer(), nullable=True),
    sa.Column('numero_titulos', sa.Integer(), nullable=True),
    sa.Column('melhor_resultado', sa.String(length=30), nullable=True),
    sa.Column('id_equipe', sa.Integer(), nullable=False),
    sa.Column('id_cidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cidade'], ['cidade.id_cidade'], ),
    sa.ForeignKeyConstraint(['id_equipe'], ['equipe.id_equipe'], ),
    sa.PrimaryKeyConstraint('id_piloto'),
    sa.UniqueConstraint('nome_piloto')
    )
    op.create_table('resultados',
    sa.Column('id_resultado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=True),
    sa.Column('pontuacao_corrida', sa.Integer(), nullable=True),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['evento.id_evento'], ),
    sa.PrimaryKeyConstraint('id_resultado')
    )
    op.create_table('resultado_piloto',
    sa.Column('id_resultado_piloto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_resultado', sa.Integer(), nullable=False),
    sa.Column('id_piloto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_piloto'], ['piloto.id_piloto'], ),
    sa.ForeignKeyConstraint(['id_resultado'], ['resultados.id_resultado'], ),
    sa.PrimaryKeyConstraint('id_resultado_piloto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultado_piloto')
    op.drop_table('resultados')
    op.drop_table('piloto')
    op.drop_table('evento')
    op.drop_table('equipe')
    op.drop_table('circuito')
    op.drop_table('cidade')
    op.drop_table('pais')
    # ### end Alembic commands ###
